-- Import other files variables
local _, L = ...;

-- classIndex: "none"
MacroCollection_GENERICS = {
  {
    ["name"] = L["Example"] .. ": " .. L["Focus"],
    ["description"] = L["This macro"] .. " " .. L["is an example for creating"] .. " " .. L["skills"] .. " '" .. L["on"] .. " " .. L["Focus"] .. "'. " .. L["These skills will be casted"] .. " " .. L["on focused target"] .. ". " .. L["If you don't have"] .. ", " .. L["they will be casted normally"] .. ".",
    ["spellID"] = "74009",
    ["macro"] = "#showtooltip YourSkill \n/stopcasting \n/cast [target=focus,exists]YourSkill;YourSkill",
    ["class"] = "none",
  },
  {
    ["name"] = L["Example"] .. ": " .. L["Mouseover"],
    ["description"] = L["This macro"] .. " " .. L["is an example for creating"] .. " " .. L["skills"] .. " '" .. L["on"] .. " " .. L["Mouseover"] .. "'. " .. L["These skills will be casted"] .. " " .. L["on mouseover target"] .. ". " .. L["If you don't have"] .. ", " .. L["they will be casted normally"] .. ".",
    ["spellID"] = "74009",
    ["macro"] = "#showtooltip YourSkill \n/stopcasting \n/cast [target=mouseover,help,nodead][]YourSkill",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mount special"],
    ["description"] = L["This macro"] .. " ".. L["allows your pet"] .. " ".. L["to make special moves"] .. ".",
    ["itemID"] = "32860",
    ["macro"] = "/mountspecial",
    ["class"] = "none",
  },
  {
    ["name"] = L["Roll dice"],
    ["description"] = L["This macro"] .. " ".. L["allows you"] .. " " .. L["to roll a pair of dice"] .. ".",
    ["itemID"] = "36862",
    ["macro"] = "/" .. L["dices"],
    ["class"] = "none",
  },
  {
    ["name"] = L["Trinkets boost"],
    ["description"] = L["This macro"] .. " " .. L["will use"] .. " " .. L["the two trinket habilities"] .. ".",
    ["itemID"] = "5862",
    ["macro"] = "/stopcasting \n/use 13 \n/use 14",
    ["class"] = "none",
  },
  {
    ["name"] = L["Use"] .. " " .. L["talents specialization"] .. " 1",
    ["description"] = L["This macro"] .. " " .. L["will use"] .. " " .. L["the first"] .. " " .. L["talents specialization"] .. " " .. L["of your"] .. " " .. L["character"] .. ".",
    ["spellID"] = "22908",
    ["macro"] = "/run SetSpecialization(1)",
    ["class"] = "none",
  },
  {
    ["name"] = L["Use"] .. " " .. L["talents specialization"] .. " 2",
    ["description"] = L["This macro"] .. " " .. L["will use"] .. " " .. L["the second"] .. " " .. L["talents specialization"] .. " " .. L["of your"] .. " " .. L["character"] .. ".",
    ["spellID"] = "22908",
    ["macro"] = "/run SetSpecialization(2)",
    ["class"] = "none",
  },
  {
    ["name"] = L["Use"] .. " " .. L["talents specialization"] .. " 3",
    ["description"] = L["This macro"] .. " " .. L["will use"] .. " " .. L["the third"] .. " " .. L["talents specialization"] .. " " .. L["of your"] .. " " .. L["character"] .. ".",
    ["spellID"] = "22908",
    ["macro"] = "/run SetSpecialization(3)",
    ["class"] = "none",
  },
  {
    ["name"] = L["Use"] .. " " .. L["talents specialization"] .. " 4",
    ["description"] = L["This macro"] .. " " .. L["will use"] .. " " .. L["the fourth"] .. " " .. L["talents specialization"] .. " " .. L["of your"] .. " " .. L["character"] .. ".",
    ["spellID"] = "22908",
    ["macro"] = "/run SetSpecialization(4)",
    ["class"] = "none",
  },
  {
    ["name"] = L["Enable AutoTrack quest"] .. "",
    ["description"] = L["This macro"] .. " " .. L["will activate"] .. " " .. L["quest autotracking"] .. "(" .. L["Need to relog"] .. ").",
    ["itemID"] = "128268",
    ["macro"] = "/console autoQuestWatch 1",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Star"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Star"] .. ".",
    ["spellID"] = "202739",
    ["macro"] = "/run SetRaidTarget(\"target\", 1);",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Circle"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Circle"] .. ".",
    ["itemID"] = "43699",
    ["macro"] = "/run SetRaidTarget(\"target\", 2);",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Diamond"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Diamond"] .. ".",
    ["itemID"] = "138875",
    ["macro"] = "/run SetRaidTarget(\"target\", 3);",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Triangle"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Triangle"] .. ".",
    ["itemID"] = "127764",
    ["macro"] = "/run SetRaidTarget(\"target\", 4);",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Moon"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Moon"] .. ".",
    ["itemID"] = "124228",
    ["macro"] = "/run SetRaidTarget(\"target\", 5);",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Square"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Square"] .. ".",
    ["itemID"] = "115806",
    ["macro"] = "/run SetRaidTarget(\"target\", 6);",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Cross"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Cross"] .. ".",
    ["itemID"] = "38295",
    ["macro"] = "/run SetRaidTarget(\"target\", 7);",
    ["class"] = "none",
  },
  {
    ["name"] = L["Mark"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Skull"],
    ["description"] = L["This macro"] .. " " .. L["will mark"] .. " " .. L["your"] .. " " .. L["target"] .. " " .. L["with"] .. " " .. L["Skull"] .. ".",
    ["itemID"] = "25125",
    ["macro"] = "/run SetRaidTarget(\"target\", 8);",
    ["class"] = "none",
  },
};
-- {
--   ["name"] = "",
--   ["description"] = "",
--   ["spellID"] = "",
--   ["macro"] = "",
--   ["class"] = "none",
-- },
